// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViagemApp.Infra.Data.SqlServer.Context;

#nullable disable

namespace ViagemApp.Infra.Data.SqlServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240918231208_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ViagemApp.Domain.Entities.CompaniaAerea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nm_compania_aerea");

                    b.HasKey("Id");

                    b.ToTable("TB_COMPANIA_AEREA", (string)null);
                });

            modelBuilder.Entity("ViagemApp.Domain.Entities.ParceriaFidelidade", b =>
                {
                    b.Property<Guid>("IdCompaniaAeria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProgramaFidelidade")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QtdLimiteCpf")
                        .HasColumnType("int")
                        .HasColumnName("qtd_cpfs");

                    b.HasKey("IdCompaniaAeria", "IdProgramaFidelidade");

                    b.HasIndex("IdProgramaFidelidade");

                    b.ToTable("TB_PARCERIA_FIDELIDADE", (string)null);
                });

            modelBuilder.Entity("ViagemApp.Domain.Entities.ProgramaFidelidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nm_programa_fidelidade");

                    b.HasKey("Id");

                    b.ToTable("TB_PROGRAMA_FIDELIDADE", (string)null);
                });

            modelBuilder.Entity("ViagemApp.Domain.Entities.ParceriaFidelidade", b =>
                {
                    b.HasOne("ViagemApp.Domain.Entities.CompaniaAerea", "CompaniaAeria")
                        .WithMany("ParceriaFidelidade")
                        .HasForeignKey("IdCompaniaAeria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViagemApp.Domain.Entities.ProgramaFidelidade", "ProgramaFidelidade")
                        .WithMany("ParceriaFidelidade")
                        .HasForeignKey("IdProgramaFidelidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompaniaAeria");

                    b.Navigation("ProgramaFidelidade");
                });

            modelBuilder.Entity("ViagemApp.Domain.Entities.CompaniaAerea", b =>
                {
                    b.Navigation("ParceriaFidelidade");
                });

            modelBuilder.Entity("ViagemApp.Domain.Entities.ProgramaFidelidade", b =>
                {
                    b.Navigation("ParceriaFidelidade");
                });
#pragma warning restore 612, 618
        }
    }
}
